name: Deploy on PR comment


on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy' }}
    steps:
    - name: Get PR SHA
      id: sha
      uses: actions/github-script@v6.0.0
      with:
        result-encoding: string
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head.sha
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.sha.outputs.result }}
    - name: React to comment
      uses: actions/github-script@v6.0.0
      with:
        script: |
          const {owner, repo} = context.issue;
          github.rest.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "rocket",
          });
    - name: Fail randomly
      id: deployment
      run: |
        echo "running deployment, v7"
        exit $((RANDOM % 2))
    - name: Message success
      if: ${{ success() }}
      uses: actions/github-script@v6.0.0
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! ✅',
          });
    - name: Message failure
      if: ${{ failure() }}
      uses: actions/github-script@v6.0.0
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment failed! ❌',
          });
